# App-specific tweaks
source = ~/.local/share/hiarchy/default/hypr/apps/browser.conf
source = ~/.local/share/hiarchy/default/hypr/apps/hyprshot.conf
source = ~/.local/share/hiarchy/default/hypr/apps/jetbrains.conf
source = ~/.local/share/hiarchy/default/hypr/apps/localsend.conf
source = ~/.local/share/hiarchy/default/hypr/apps/pip.conf
source = ~/.local/share/hiarchy/default/hypr/apps/qemu.conf
source = ~/.local/share/hiarchy/default/hypr/apps/retroarch.conf
source = ~/.local/share/hiarchy/default/hypr/apps/steam.conf
source = ~/.local/share/hiarchy/default/hypr/apps/geforce.conf
source = ~/.local/share/hiarchy/default/hypr/apps/system.conf
source = ~/.local/share/hiarchy/default/hypr/apps/telegram.conf
source = ~/.local/share/hiarchy/default/hypr/apps/terminals.conf
source = ~/.local/share/hiarchy/default/hypr/apps/walker.conf
source = ~/.local/share/hiarchy/default/hypr/apps/webcam-overlay.conf
