exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- fcitx5
exec-once = uwsm-app -- swaybg -i ~/.config/hiarchy/current/background -m fill
exec-once = uwsm-app -- swayosd-server
exec-once = hiarchy-state-toggles get | grep auto-hide-waybar >/dev/null && uwsm-app -- hiarchy-waybar-auto-hide --side top &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hiarchy-cmd-first-run
exec-once = hiarchy-main-monitor-detect

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
