source /usr/share/zinit/zinit.zsh

zinit snippet OMZP::git
zinit snippet OMZP::starship

zinit light djui/alias-tips

zinit light zsh-users/zsh-history-substring-search

zinit load zdharma-continuum/history-search-multi-word

zinit light zsh-users/zsh-syntax-highlighting

zinit light zsh-users/zsh-autosuggestions

zinit light zsh-users/zsh-completions

zinit light hlissner/zsh-autopair

# zinit light Aloxaf/fzf-tab

source ~/.local/share/hiarchy/default/zsh/rc
