general {
    lock_cmd = hiarchy-lock-screen                         # lock screen
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on             # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

listener {
    timeout = 300                                          # 5 mins (300 seconds)
    # Save the current brightness, drop it to 30%, and start screensaver (if not locked)
    on-timeout = bash -c 'brightnessctl -s set 30%; pidof hyprlock || hiarchy-launch-screensaver'

    # When you move the mouse: Restore brightness AND kill the screensaver
    on-resume = bash -c 'brightnessctl -r; pkill -SIGTERM -f org.hiarchy.screensaver'
}

listener {
    timeout = 600                                          # 10 mins (600 seconds)
    on-timeout = loginctl lock-session                     # lock screen when timeout has passed
}

listener {
    timeout = 605                                          # 10.1 mins (605 seconds)
    on-timeout = hyprctl dispatch dpms off                 # screen off
    on-resume = hyprctl dispatch dpms on                   # screen on when activity is detected
}
