source = ~/.config/hiarchy/current/theme/hyprlock.conf
source = ~/.config/hiarchy/current/monitor.conf

general {
    ignore_empty_input = true
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

auth {
    fingerprint:enabled = false
}

background {
    monitor =
    path = ~/.config/hiarchy/current/background
    color = rgb(0,0,0)

    blur_size = 3
    blur_passes = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.6000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Time
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = $on_secondary_container
    font_size = 110
    font_family = JetBrainsMono Nerd Font ExtraBold

    # Anchored to the top, pushed down slightly
    position = 0, -100
    halign = center
    valign = top
}

# Day-Month-Date
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $on_secondary_container
    font_size = 18
    font_family = JetBrainsMono Nerd Font Bold

    # Anchored right below the time
    position = 0, -290
    halign = center
    valign = top
}

# Profile Image
image {
    monitor = $main_monitor
    path = $HIARCHY_PATH/icon.png
    size = 140
    rounding = -1
    border_size = 0

    position = 0, 80
    halign = center
    valign = center
}

# User Name
label {
    monitor = $main_monitor
    text = Welcome back, $USER
    color = $secondary
    font_size = 16
    font_family = JetBrainsMono Nerd Font Bold

    position = 0, -30
    halign = center
    valign = center
}

# Password Input
input-field {
    monitor = $main_monitor
    size = 280, 45    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.4
    dots_center = true

    # Windows 11 style inputs are subtle pills
    rounding = 22
    outer_color = $outer_color
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = $font_color

    fade_on_empty = true
    placeholder_text = <i>Enter Password...</i>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    position = 0, -110
    halign = center
    valign = center
}

# --- POWER OFF (Far Right) ---
label {
    monitor = $main_monitor
    text = <span>  󰐥  </span>
    color = $on_secondary_container
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    onclick = hiarchy-cmd-shutdown

    position = -40, 40
    halign = right
    valign = bottom
}

# --- REBOOT (Middle Right) ---
label {
    monitor = $main_monitor
    text = <span>  󰜉  </span>
    color = $on_secondary_container
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    onclick = hiarchy-cmd-reboot

    position = -100, 40
    halign = right
    valign = bottom
}

# --- SUSPEND (Inner Right) ---
label {
    monitor = $main_monitor
    text = <span>  󰤄  </span>
    color = $on_secondary_container
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    onclick = systemctl suspend

    position = -160, 40
    halign = right
    valign = bottom
}
