# ================================================================
# SOURCES & GENERAL
# ================================================================
source = ~/.config/hiarchy/current/theme/hyprlock.conf
source = ~/.config/hiarchy/current/monitor.conf

general {
    ignore_empty_input = true
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

auth {
    fingerprint:enabled = false
}

# ================================================================
# BACKGROUND
# ================================================================
background {
    monitor =
    path = ~/.config/hiarchy/current/background
    color = rgb(0,0,0)

    blur_size = 3
    blur_passes = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.6000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Time
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = $on_secondary_container
    font_size = 130
    font_family = JetBrainsMono Nerd Font ExtraBold

    position = 0, 260
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = $on_secondary_container
    font_size = 24
    font_family = JetBrainsMono Nerd Font Bold

    position = 0, 130
    halign = center
    valign = center
}

image {
    monitor = $main_monitor
    path = $HIARCHY_PATH/icon.png
    size = 110
    rounding = -1
    border_size = 4
    border_color = $outer_color

    rotate = 0
    reload_time = -1
    reload_cmd =

    position = 0, -10
    halign = center
    valign = center
}

# Greeting
label {
    monitor = $main_monitor
    text = Welcome back, $USER
    color = $secondary
    font_size = 16
    font_family = JetBrainsMono Nerd Font Italic

    position = 0, -100
    halign = center
    valign = center
}

input-field {
    monitor = $main_monitor
    size = 250, 50
    outline_thickness = 3

    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true

    rounding = 22
    outer_color = $outer_color
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = $font_color

    fade_on_empty = true
    placeholder_text = <i>Enter Password...</i>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    position = 0, 160
    halign = center
    valign = bottom
}

# --- SUSPEND (Left) ---
shape {
    monitor = $main_monitor
    size = 80, 80
    color = rgba(255, 255, 255, 0.05)
    border_size = 2
    border_color = rgba(255, 255, 255, 0.1)
    rounding = 20
    position = -100, 40
    halign = center
    valign = bottom
}
label {
    monitor = $main_monitor
    text = <span>  󰤄  </span>
    color = rgba(255, 255, 255, 0.8)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    onclick = systemctl suspend
    position = -100, 55
    halign = center
    valign = bottom
}

# --- REBOOT (Center) ---
shape {
    monitor = $main_monitor
    size = 80, 80
    color = rgba(255, 255, 255, 0.05)
    border_size = 2
    border_color = rgba(255, 255, 255, 0.1)
    rounding = 20
    position = 0, 40
    halign = center
    valign = bottom
}
label {
    monitor = $main_monitor
    text = <span>  󰜉  </span>
    color = rgba(255, 255, 255, 0.8)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    onclick = hiarchy-cmd-reboot
    position = 0, 55
    halign = center
    valign = bottom
}

# --- POWER OFF (Right) ---
shape {
    monitor = $main_monitor
    size = 80, 80
    color = rgba(255, 255, 255, 0.05)
    border_size = 2
    border_color = rgba(255, 255, 255, 0.1)
    rounding = 20
    position = 100, 40
    halign = center
    valign = bottom
}
label {
    monitor = $main_monitor
    text = <span>  󰐥  </span>
    color = rgba(255, 255, 255, 0.8)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    onclick = hiarchy-cmd-screenshot fullscreen clipboard
    position = 100, 55
    halign = center
    valign = bottom
}
