[tools]
cloudflared = "latest"
dotnet = "9.0.311"
node = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
terraform = "latest"
trivy = "latest"
tflint = "latest"
kubectl= "latest"
kubeseal = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
"github:jesseduffield/lazygit" = "latest"
"github:jesseduffield/lazydocker" = "latest"
docker-compose = "latest"
docker-cli = "latest"
